//Users
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_PROFILE_VIEW_REQUEST = 'USER_PROFILE_VIEW_REQUEST';
export const USER_PROFILE_VIEW_SUCCESS = 'USER_PROFILE_VIEW_SUCCESS';
export const USER_PROFILE_VIEW_FAIL = 'USER_PROFILE_VIEW_FAIL';
export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST';
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS';
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL';
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET';

//AdminUsers
export const ADMIN_USERS_LIST_REQUEST = 'ADMIN_USERS_LIST_REQUEST';
export const ADMIN_USERS_LIST_SUCCESS = 'ADMIN_USERS_LIST_SUCCESS';
export const ADMIN_USERS_LIST_FAIL = 'ADMIN_USERS_LIST_FAIL';
export const ADMIN_USERS_LIST_RESET ='ADMIN_USERS_LIST_RESET';
export const ADMIN_USERS_DETAIL_REQUEST = 'ADMIN_USERS_DETAIL_REQUEST';
export const ADMIN_USERS_DETAIL_SUCCESS = 'ADMIN_USERS_DETAIL_SUCCESS';
export const ADMIN_USERS_DETAIL_FAIL = 'ADMIN_USERS_DETAIL_FAIL';
export const ADMIN_USERS_UPDATE_REQUEST = 'ADMIN_USERS_UPDATE_REQUEST';
export const ADMIN_USERS_UPDATE_SUCCESS = 'ADMIN_USERS_UPDATE_SUCCESS';
export const ADMIN_USERS_UPDATE_FAIL = 'ADMIN_USERS_UPDATE_FAIL';
export const ADMIN_USERS_ADD_NEW_REQUEST = 'ADMIN_USERS_ADD_NEW_REQUEST';
export const ADMIN_USERS_ADD_NEW_SUCCESS = 'ADMIN_USERS_ADD_NEW_SUCCESS';
export const ADMIN_USERS_ADD_NEW_FAIL = 'ADMIN_USERS_ADD_NEW_FAIL';